import { Footer } from '@/components/ui/footer'
import { NextAuthProvider } from '@/providers/auth'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex h-full flex-col">
          <NextAuthProvider>
            <div className="flex-1">{children}</div>
            <Footer />
          </NextAuthProvider>
        </div>
      </body>
    </html>
  )
}
